In [119]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from selenium.webdriver.support.wait import WebDriverWait

In [121]:
driver = webdriver.Chrome()
driver.get('https://www.nba.com/stats/players/traditional?Season=2023-24')

In [122]:
df2 = pd.DataFrame()

In [125]:
table = driver.find_element(By.CSS_SELECTOR, 'table[class="Crom_table__p1iZz"]')

In [126]:
while True:
    a = [[i.text for i in j.find_elements(By.CSS_SELECTOR, 'td')] for j in table.find_elements(By.CSS_SELECTOR, 'tr')]
    df2 = pd.concat((df2, pd.DataFrame(a)))
    try:
        next_page = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[data-pos='next']"))).click()
    except:
        break
    print(df2.shape)

(51, 30)
(102, 30)
(153, 30)
(204, 30)

In [127]:
df2

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,1,Joel Embiid,PHI,30,6,2,4,41.4,33.0,9.8,...,10.8,5.7,4.2,1.2,1.5,3.3,58.3,4.0,1.0,7.7
2,2,Jalen Brunson,NYK,27,10,6,4,40.8,32.9,11.6,...,3.8,7.6,3.0,1.0,0.2,2.1,49.5,3.0,0.0,0.1
3,3,Anthony Edwards,MIN,22,8,6,2,40.0,32.1,11.8,...,6.5,5.6,3.6,1.6,0.9,2.4,52.2,0.0,0.0,7.6
4,4,Damian Lillard,MIL,33,4,1,3,39.1,31.3,8.5,...,3.3,5.0,2.3,1.0,0.0,2.0,43.4,0.0,0.0,-8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,195,Orlando Robinson,MIA,23,1,0,1,2.5,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,2.7,0.0,0.0,3.0
9,195,Svi Mykhailiuk,BOS,26,4,3,1,4.3,0.0,0.0,...,0.8,0.3,0.5,0.3,0.0,0.5,1.5,0.0,0.0,0.0
10,195,T.J. Warren,MIN,30,3,2,1,3.8,0.0,0.0,...,1.0,0.3,0.0,0.0,0.0,0.0,1.7,0.0,0.0,2.3
11,195,Thaddeus Young,PHX,35,1,0,1,3.6,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.0
12,195,Thanasis Antetokounmpo,MIL,31,2,0,2,2.4,0.0,0.0,...,0.0,0.0,0.0,0.5,0.5,0.5,3.0,0.0,0.0,1.0

In [128]:
df2 = df2[1:]

In [133]:
df2 = df2.rename(columns={
    0: 'Rank'
    1: 'Player',
    2: 'Team',
    3: 'Age',
    4: 'GP',
    5: 'Wins',
    6: 'Losses',
    7: 'MIN',
    8: 'PTS',
    9: 'FGM',
    10: 'FGA',
    11: 'FG%',
    12: '3PM',
    13: '3PA',
    14: '3P%',
    15: 'FTM',
    16: 'FTA',
    17: 'FT%',
    18: 'OREB',
    19: 'DREB',
    20: 'REB',
    21: 'AST',
    22: 'TOV',
    23: 'STL',
    24: 'BLK',
    25: 'PF',
    26: 'FP',
    27: 'DD2',
    28: 'TD3',
    29: 'PlusMinus'
})

In [139]:
df2 = df2.set_index('Rank')

In [140]:
df2

,Player,Team,Age,GP,Wins,Losses,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,PF,FP,DD2,TD3,PlusMinus
Rank,,,,,,,,,,,,,,,,,,,,,
1,Joel Embiid,PHI,30,6,2,4,41.4,33.0,9.8,22.2,...,10.8,5.7,4.2,1.2,1.5,3.3,58.3,4.0,1.0,7.7
2,Jalen Brunson,NYK,27,10,6,4,40.8,32.9,11.6,26.2,...,3.8,7.6,3.0,1.0,0.2,2.1,49.5,3.0,0.0,0.1
3,Anthony Edwards,MIN,22,8,6,2,40.0,32.1,11.8,21.0,...,6.5,5.6,3.6,1.6,0.9,2.4,52.2,0.0,0.0,7.6
4,Damian Lillard,MIL,33,4,1,3,39.1,31.3,8.5,20.3,...,3.3,5.0,2.3,1.0,0.0,2.0,43.4,0.0,0.0,-8.8
5,Tyrese Maxey,PHI,23,6,2,4,44.6,29.8,11.0,23.0,...,5.2,6.8,2.2,0.8,0.3,2.7,47.6,1.0,0.0,-1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Orlando Robinson,MIA,23,1,0,1,2.5,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,2.7,0.0,0.0,3.0
195,Svi Mykhailiuk,BOS,26,4,3,1,4.3,0.0,0.0,0.8,...,0.8,0.3,0.5,0.3,0.0,0.5,1.5,0.0,0.0,0.0
195,T.J. Warren,MIN,30,3,2,1,3.8,0.0,0.0,0.7,...,1.0,0.3,0.0,0.0,0.0,0.0,1.7,0.0,0.0,2.3
195,Thaddeus Young,PHX,35,1,0,1,3.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.0
195,Thanasis Antetokounmpo,MIL,31,2,0,2,2.4,0.0,0.0,0.0,...,0.0,0.0,0.0,0.5,0.5,0.5,3.0,0.0,0.0,1.0

In [148]:
df2.iloc[:, 2:6] = df2.iloc[:, 2:6].astype(pd.Int64Dtype())

In [149]:
df2.iloc[:, 6:] = df2.iloc[:, 6:].astype(pd.Float64Dtype())

In [163]:
df2.to_csv('2024_playoffs_data')