In [119]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
from selenium.webdriver.support.wait import WebDriverWait

In [65]:
driver = webdriver.Chrome()
driver.get('https://www.nba.com/stats/alltime-leaders')

In [66]:
table = driver.find_element(By.CSS_SELECTOR, 'table[class="Crom_table__p1iZz"]')

In [67]:
df = pd.DataFrame()

In [75]:
while True:
    a = [[i.text for i in j.find_elements(By.CSS_SELECTOR, 'td')] for j in table.find_elements(By.CSS_SELECTOR, 'tr')]
    df = pd.concat((df, pd.DataFrame(a)))
    try:
        next_page = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[data-pos='next']"))).click()
    except:
        break
    print(df.shape)

(255, 23)
(306, 23)
(357, 23)
(408, 23)
(459, 23)
(510, 23)
(561, 23)
(612, 23)
(663, 23)
(714, 23)
(765, 23)
(816, 23)
(867, 23)
(918, 23)
(969, 23)
(1020, 23)
(1071, 23)
(1122, 23)
(1173, 23)
(1224, 23)
(1275, 23)
(1326, 23)
(1377, 23)
(1428, 23)
(1479, 23)
(1530, 23)
(1581, 23)
(1632, 23)
(1683, 23)
(1734, 23)
(1785, 23)
(1836, 23)
(1887, 23)
(1938, 23)
(1989, 23)
(2040, 23)

KeyboardInterrupt:

In [76]:
df

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,1,LeBron James,"1,492",56596,40474,14837,29313,50.6,2410,6926,...,73.6,1727,9458,11185,11009,2275,1111,5211,54.7,58.9
2,2,Kareem Abdul-Jabbar,"1,560",57446,38387,15837,28307,55.9,1,18,...,72.1,2975,9394,17440,5660,1160,3189,2527,55.9,59.2
3,3,Karl Malone,"1,476",54852,36928,13528,26210,51.6,85,310,...,74.2,3562,11406,14968,5248,2085,1145,4524,51.8,57.7
4,4,Kobe Bryant,"1,346",48643,33643,11719,26200,44.7,1827,5546,...,83.7,1499,5548,7047,6306,1944,640,4010,48.2,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,1796,Donnie Butcher,279,5085,1696,610,1535,39.7,-,-,...,62.9,-,-,821,585,-,-,-,39.7,45.4
47,1797,Scott Lloyd,372,5638,1694,647,1521,42.5,2,7,...,71.8,422,692,1114,356,100,73,304,42.6,48.0
48,1798,Jerian Grant,279,4998,1692,593,1442,41.1,174,539,...,77.0,92,437,529,805,205,33,274,47.2,51.8
49,1799,Courtney Alexander,187,4067,1690,655,1552,42.2,41,121,...,81.3,124,285,409,227,111,18,203,43.5,48.7
50,1799,Davion Mitchell,227,4624,1690,679,1565,43.4,221,675,...,70.3,68,298,366,632,116,42,219,50.4,51.7

In [77]:
df = df.rename(columns={
    0: '#',
    1: 'Player',
    2: 'GP',
    3: 'MIN',
    4: 'PTS',
    5: 'FGM',
    6: 'FGA',
    7: 'FG%',
    8: '3PM',
    9: '3PA',
    10: '3P%',
    11: 'FTM',
    12: 'FTA',
    13: 'FT%',
    14: 'OREB',
    15: 'DREB',
    16: 'REB',
    17: 'AST',
    18: 'STL',
    19: 'BLK',
    20: 'TOV',
    21: 'EFG%',
    22: 'TS%'
})

In [79]:
df = df[1:]

In [87]:
df

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFG%,TS%
1,1,LeBron James,"1,492",56596,40474,14837,29313,50.6,2410,6926,...,73.6,1727,9458,11185,11009,2275,1111,5211,54.7,58.9
2,2,Kareem Abdul-Jabbar,"1,560",57446,38387,15837,28307,55.9,1,18,...,72.1,2975,9394,17440,5660,1160,3189,2527,55.9,59.2
3,3,Karl Malone,"1,476",54852,36928,13528,26210,51.6,85,310,...,74.2,3562,11406,14968,5248,2085,1145,4524,51.8,57.7
4,4,Kobe Bryant,"1,346",48643,33643,11719,26200,44.7,1827,5546,...,83.7,1499,5548,7047,6306,1944,640,4010,48.2,55.0
5,5,Michael Jordan,"1,072",41010,32292,12192,24537,49.7,581,1778,...,83.5,1668,5004,6672,5633,2514,893,2924,50.9,56.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,1796,Donnie Butcher,279,5085,1696,610,1535,39.7,-,-,...,62.9,-,-,821,585,-,-,-,39.7,45.4
47,1797,Scott Lloyd,372,5638,1694,647,1521,42.5,2,7,...,71.8,422,692,1114,356,100,73,304,42.6,48.0
48,1798,Jerian Grant,279,4998,1692,593,1442,41.1,174,539,...,77.0,92,437,529,805,205,33,274,47.2,51.8
49,1799,Courtney Alexander,187,4067,1690,655,1552,42.2,41,121,...,81.3,124,285,409,227,111,18,203,43.5,48.7
50,1799,Davion Mitchell,227,4624,1690,679,1565,43.4,221,675,...,70.3,68,298,366,632,116,42,219,50.4,51.7

In [93]:
df.loc[:, 'GP'] = df['GP'].str.replace(',', '')

In [97]:
pd.to_numeric(df['#'])

1        1.0
2        2.0
3        3.0
4        4.0
5        5.0
       ...
46    1796.0
47    1797.0
48    1798.0
49    1799.0
50    1799.0
Name: #, Length: 2039, dtype: float64

In [103]:
df.iloc[:, 0] = df.iloc[:, 0].astype(pd.Int64Dtype())

In [104]:
df.columns

Index(['#', 'Player', 'GP', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%', '3PM', '3PA',
       '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK',
       'TOV', 'EFG%', 'TS%'],
      dtype='object')

In [107]:
df = df.replace('-', None)

In [108]:
df.iloc[:, 2:7] = df.iloc[:, 2:7].astype(pd.Int64Dtype())

In [109]:
df.iloc[:, 7] = df.iloc[:, 7].astype(pd.Float64Dtype())

In [110]:
df.iloc[:, 8:10] = df.iloc[:, 8:10].astype(pd.Int64Dtype())

In [112]:
df.iloc[:, 10] = df.iloc[:, 10].astype(pd.Float64Dtype())

In [113]:
df.iloc[:, 11:13] = df.iloc[:, 11:13].astype(pd.Int64Dtype())

In [114]:
df.iloc[:, 13] = df.iloc[:, 13].astype(pd.Float64Dtype())

In [ ]:
df.iloc[:, 14:] = df.iloc[:, 0].astype(pd.Int64Dtype())

In [ ]:
df.to_csv('nbadata.csv')